### ISSUE TITLE
5:5 p.m.

### ISSUE THREAD

**Issue by remline** [standardebooks/apsley-cherry-garrard_the-worst-journey-in-the-world#5]
The orthography 5:5 p.m. is confusing. The Internet Archive copy has 5.5 p.m. Perhaps the author is abbreviating 5:50 p.m. or 5:30 p.m.? Or perhaps it was a printer's error?

References:
https://archive.org/details/worstjourneyinwo02/page/398/mode/1up
chapter-12.xhtml

**Comment by acabal** [comment]
I agree, I'll revert it to 5.5 in our edition as it's unclear what it's referring to.
